- network.zig
I initially started adapting all of the `std.net` code for non-libc linux as well but it is a lot, we fall back to using it from std.net for now.  
However testing this without libc on WSL fails with `temporaryNameServerFailure`, not sure if this is a WSL thing or a `std.net` bug (the libc version works).  
Adding `connectToHost` soon.
> Added getEndpointList

- network.zig
- testsuite.zig
Here is a simple test that listens on IPv6 loopback and accepts a single client as a small test.
```zig
const std = @import("std");
const network = @import("network.zig");
test "Listen on loopback ipv6" {
try network.init();
defer network.deinit();
var server = try network.Socket.create(.ipv6, .tcp);
defer server.close();
std.debug.warn("Loopback addr: {}\n", .{network.Address.IPv6.loopback});
try server.bind(.{
.address = .{ .ipv6 = network.Address.IPv6.loopback },
.port = 0,
});
try server.listen();
const endpt = try server.getLocalEndPoint();
std.debug.warn("Listening on {}\n", .{endpt});
// Make a client!
const client = try network.Socket.create(.ipv6, .tcp);
try client.connect(endpt);
defer client.close();
const msg = "Hello from the same process";
try …
```
> IPv6 support 

- network.zig
The usage of `getsockname` in `getpeername` made it so that when getting a remote endpoint we instead got the local endpoint.
This seems like it might've been a copy-paste error.
> `getpeername` instead of `getsockname` in `getpeername`

- network.zig
On BSD you set the signal options on the socket itself, rather than on each message. Unfortunately the bits SO_NOSIGPIPE are not set upstream for macos (they are for BSD), so I defined it within the function itself for now.
This PR fixes compilation error on MacOS and allows the testsuite to be run again. I have not yet tested async yet.
> Fix SIGPIPE on MacOS

- async.zig
- network.zig
This PR adds async support by setting the socket flags explicitly. This cooperates with the std as it will set the corresponding Darwin flag accordingly (using a shim).
Poll() works the same on Darwin/BSD as Linux therefore I created an alias to LinuxOsLogic. I don't have a BDS system to test on so didn't add support for that.
> MacOs async and poll() support

- network.zig
On MacOs accept() doesn't support for any flags. I also added the SOCK_CLOEXEC flag to socket creation as this fixes a race condition when another thread writes to a socket when the socket is being opened.
> Fixes accept() on MacOs

- network.zig
Since some of the allocator interface was changed (recently?) I think a change like this one is needed. The specifics I'm not so sure about; `.exact` etc.
> Switch to `reallocAdvanced` instead of `allignedRealloc`

- network.zig
With a newer commit if you use an invalid calling convention for the platform you get a compile error instead of it figuring it out. Therefore this pull request makes it so that we use a variable that will contain the correct calling convention
> Switch from using .Stdcall directly to using WINAPI

- .github/workflows/build.yml
- build.zig
- examples/discovery/client.zig
- examples/discovery/server.zig
- examples/multicast_udp.zig
- network.zig
- testsuite.zig
- Add simple UDP listener
- On each socket, store 'connected_to' and 'bound_to' endpoints
> Adding UDP multicast example

- network.zig
Hi!
I was trying zig-network on Windows and found that when I called `receiveFrom` over UDP, I always got a `WSAEOPNOTSUPPP` error. The reason for this is that the `lpFlags` argument to `WSARecvFrom` and `recvfrom` is incorrect. I fixed it so that it works fine on Windows. 
[WSARecvFrom](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsarecvfrom)
[recvfrom](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-recvfrom)
> Fix "WSAEOPNOTSUPP" error in Socket.receiveFrom

- network.zig
Adds a "peek" function using MSG_PEEK to gather information on the data held in the stream state. Can be used to check things like Packet IDs or VarInt lengths and then determine a proper buffer reallocation for the size.
> Add socket.peek()

- network.zig
- testsuite.zig
Implement setTimeout function.
It is very useful, if you don't want to use async IO, and use blocking IO but with timeouts - to prevent your program from infinite IO blocking.
It is tested at least on Linux and Windows 11. Should be OK with other OS I think.
Need a code review though.
> setTimeout function

- network.zig
Basically the new reallocAdvanced uses the alignment of the old memory.
Closes #50
> Update reallocAdvanced call for new signature

- .github/workflows/build.yml
- build.zig
- examples/udp_broadcast.zig
- network.zig
1. Adds the `setBroadcast` function to `network.zig` to enable or disable the `SO_BROADCAST` socket option for UDPv4
2. Adds a very basic example to demonstrate usage of _setBroadcast_
3. Adds example to _build.zig_ and github workflow
Ref. [SO_BROADCAST setsockopt for UDP socket](https://github.com/MasterQ32/zig-network/issues/52)
> Add setBroadcast function to enable or disable SO_BROADCAST socket option for UDPv4

- network.zig
Fix the build-in methods to use the new style using result location types.
Replace removed `std.cstr.addNullByte` with suggested alternative.
> Fix buildins using result location types.

- network.zig
- testsuite.zig
- Disable SIO_UDP_CONNRESET behaviour  for UDP sockets
- Add test to catch error `error.Unexpected: GetLastError(10054): An existing connection was forcibly closed by the remote host.` if SIO_UDP_CONNRESET disable code is not present.
Example of error thrown without this PR:
```
error.Unexpected: GetLastError(10054): An existing connection was forcibly closed by the remote host.
C:\zig\current\lib\std\os\windows.zig:2335:27: 0x7ff7d228a286 in unexpectedWSAError (test.exe.obj)
return unexpectedError(@as(Win32Error, @enumFromInt(@intFromEnum(err))));
^
D:\ZigProjects\zig-network\network.zig:1485:60: 0x7ff7d22943a8 in recvfrom (test.exe.obj)
else => |err| return unexpectedWSAError(err),
^
D:\ZigProjects\zig-network\network.zig:505:36: 0x7ff7d22d55a7 in receiveFrom (test.exe.obj)
const len = …
```
> disable SIO_UDP_CONNRESET behaviour for UDP

- network.zig
Master branch standard library currently uses `big` and `little` fields for the `Endian` enum, changed from the previous `Big` and `Little` fields. Additionally, the `writeIntBig`/`writeIntLittle` functions have been removed and now the `writeInt` function must be used instead.
> Update to latest master `Endian` enum changes

- build.zig.zon
Adding a `build.zig.zon` here allows specifying paths to consider for the package hash. Projects depending on `zig-network` through the Zig package manager will be able to recalculate their hash less frequently when tracking `master`, to only changes that impact:
1. The build system
2. Packaging
3. The actual source
4. Testing
5. License 
Edit: wasn't sure what to put for the version so left it at 0.1.0.
> Add `build.zig.zon` for package hash

- network.zig
Necessary for compilation on latest Zig master
> fix: Update deprecated `std.mem.split` use

- network.zig
- testsuite.zig
Implements IPv6 parsing. More detailed information about parsing spec is in `parse` function doc comment. Some test cases were added for sanity check, but the tests can be made far more rigorous; as of now, it is a bit inconvenient to test as the actual IPv6 `value` is a length-16 array of bytes, which is quite tedious to initialize. 
Resolves #54
> IPv6 parsing

- LICENSE
Minor typo in license file name spelling (at least not matching content of "MIT License" at top of file). Also updated years to be a range as per [FSF recommendation](https://www.gnu.org/licenses/gpl-howto.en.html) under the consideration that commits have been published every year since 2020.
> docs: Rename LICENCE typo to LICENSE, update years

- network.zig
- testsuite.zig
Noticed that #88 broke Windows `SocketSet` functionality, but it wasn't caught by any tests. Added coverage for `SocketSet` functions and polling. Also added one additional check to the "Connect to an echo server" test (expecting that the read message from the socket should match the write message), and changed allocator usage to `std.testing.allocator` instead of the previous `page_allocator`. Reverted pertinent polling-related parts of #88.
> Fix Windows polling

- .github/workflows/build.yml
- .gitignore
- network.zig
- testsuite.zig
this pr fixes #92 
- fixed compilation for zig0.14.0 (actually for linux - zig-linux-x86_64-**0.14.0-dev**.1694+3b465ebec)
- unmaintained *goto-bus-stop/setup-zig* was replaced with **mlugg/setup-zig**
> Failed compilation for zig0.14.0

- .github/workflows/build.yml
- network.zig
- testsuite.zig
this pr fixes #69 
- added test for the case
- intercepts **ISCONN** status returned by *.darwin* and retries sendto with null destination address
> Fix  Darwin: connection-mode socket was connected already #69 

- network.zig
Darwin part of `sendto` doesn't compile (!); this fixes it.
> sendto: ConnectionRefused isn't a valid Send.

- network.zig
- testsuite.zig
Thanks for the great work!
I just found the EndPoint couldn't parse IPv6 address properly because the position of colons. And created a simple fix.
> fix: ipv6 parse in EndPoint

- network.zig
This was inside only setWriteTimeout on Non-Windows systems inside the Socket struct.
> Fixed a bug where the field-names of certain variables were wrong.
